---

name: dressca-root-frontend CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - 'samples/Dressca/dressca-frontend/*.*'
      - '.github/workflows/samples-dressca-root-frontend-ci.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: samples/Dressca/dressca-frontend/

jobs:
  check:
    name: Dressca モノレポのルートプロジェクトのチェック
    runs-on: ubuntu-latest
    env:
      NO_COLOR: "1"  # 文字化け防止のためカラーコードを出力しない
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - name: Use Node.js LTS
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version: lts/*
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: npm
      - name: node パッケージのインストール
        run: npm ci
      - id: run-format
        name: format の実行
        run: npm run format:ci:root >> /var/tmp/format-result.txt 2>&1

      - name: format の結果出力
        if: ${{ success() || (failure() && steps.run-format.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/format-result.txt
          header: 'format の結果 :pen:'